name: CI

on:
  push:
  pull_request:

jobs:
  flake:
    runs-on: ubuntu-latest
    env:
      ACTIONS_CACHE_URL: ""
      ACTIONS_RUNTIME_TOKEN: ""
      ACTIONS_RUNTIME_URL: ""
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Check flake
        run: nix flake check
